### ISSUE TITLE
Alias for table (MSSQL) doesn't show columns

### ISSUE THREAD

**Issue by kirill-gerasimenko** [kostafey/ejc-sql#34]
Hi,

I've got ejc-sql installed into Emacs 25.3.1 with Spacemacs on Windows 10. 
I've installed JDBC driver (version 6.2, the latest one) as explained in the documentation.
I'am able to connect to the database, do queries etc.

But when I try such code:
```sql
select
  *
from
  dbo.Entity as e
where
  e.
```
I don't get autocomplete on the last line. If I put there proper value and execute - everything works.

Please advise.

PS: if you need more information please let me know and I'll provide it.

Best regards,
Kirill

**Comment by kostafey** [comment]
Autocompletion for aliases doesn't work yet. It will be implemented in future versions.
For full names, it should work as expected:
```sql
select
  *
from
  dbo.Entity
where
  dbo.Entity.|
```

**Comment by kirill-gerasimenko** [comment]
Thanks for your response and great tool!

Looking forward to the new version :)

**Comment by kostafey** [comment]
@kirill-gerasimenko could you check autocompletion for aliases, please?

**Comment by kirill-gerasimenko** [comment]
Hi,

I've checked auto-completion for the case I've described and it works!
Thanks a lot!

For this however it doesn't
``` sql
```

**Comment by kirill-gerasimenko** [comment]
Hi,

I've checked auto-completion for the case I've described above and it works!
Thanks a lot!

For this however it doesn't
``` sql
select
  t.Id,
  t.Name,
  t.<here nothing appears>
from (select a.Field1 id, a.Field2 name, a.Field1 o from dbo.Entity a) t
```

**Comment by kostafey** [comment]
Check the last example autocompletion case, please.

**Comment by kirill-gerasimenko** [comment]
It works now! Thanks a lot!

I don't know if it is important - the auto-completion suggestions are in lower case, so if `Field2` is the original one - the suggested one is `field2`. Also there is a minor one with autocomplete - it also suggests statements (like if you type `t.a` - you'll have `AND` in the suggestion), may be it's by design.
Sorry for disturbing you with these micro details

**Comment by kostafey** [comment]
@kirill-gerasimenko, could you check all related to this issue cases is fixed in the last version, please?

**Comment by kirill-gerasimenko** [comment]
Hi, I'll do that and let you know!

**Comment by kirill-gerasimenko** [comment]
Hi, 

First case with alias works well. The second one with sub-query - as well works as expected (I've tested with different combinations like aliases in sub-queries and so on), and case of the letters also corresponds to the case in the sub-query. 

The problem with auto-completion of keywords etc. seems like is still there: 

![image](https://user-images.githubusercontent.com/3036330/33782394-d945b90e-dc58-11e7-8b20-63cc86c4b074.png)

You see - in this  case `iD` is not in the list (case-sensitive?), that's the first thing, the second - extra keywords. On the other hand when you just type `t.` - auto-complete list has proper values from the sub-query.

![image](https://user-images.githubusercontent.com/3036330/33782528-6034a678-dc59-11e7-8438-47fcbe57526c.png)

I hope this helps, if you need more details please let me know.

Thanks!

**Comment by kostafey** [comment]
Thank you for patience. Could you check again, please?

**Comment by kirill-gerasimenko** [comment]
Hi,

![image](https://user-images.githubusercontent.com/3036330/35926404-5d1c311e-0c28-11e8-9051-885582fa7dcd.png)

It looks like `INSERT` is gone, but `INFROMATION_SCHEMA` is still present.

Sorry for this taking so long!

**Comment by kostafey** [comment]
@kirill-gerasimenko, looks fixed for schemas. Check again, please.
